### PR TITLE
Debian updates, drop of SCPI

### PR DESCRIPTION
**Pull request by hrw**

### CODE REVIEW

**Review by suihkulokki — COMMENTED** [review]
Will this increase the delta to debian, or do we intent to submit this to debian? eg are these options useful for any debian users?

**Comment by hrw** [comment]
This will make delta smaller as Debian does not enable SCPI/MHU like we did.

**Comment by hrw** [comment]
This last change was for 4.19.14 build (not yet in Debian).

**Comment by hrw** [comment]
Use patch from Debian kernel team rather than mine.

**Pull request merged**
